version: '3'

services:
  backend:
    image: motion_ref:latest
    ports:
      - 8000:8000
    env_file:
      - ./env/dev.env
    volumes:
      - static-files:/static-files
      - media-files:/media-files
      - frontend:/frontend/build
    command: "sh /scripts/dev.sh"
    depends_on:
      - postgres


  postgres:
    image: postgres:latest
    ports:
      - 5433:5432
    env_file:
      - ./env/dev.env
    volumes:
#    - ./postgres_volume:/var/lib/postgresql/data
    - ./postgres-data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/def.conf:/etc/nginx/conf.d/default.conf
      - static-files:/static-files
      - media-files:/media-files
#      - /etc/letsencrypt:/etc/letsencrypt
      - frontend:/frontend

volumes:
  postgres_volume:
  static-files:
  media-files:
  frontend:
